### ISSUE TITLE
Font on Printed ID Card Sheet Style

### ISSUE THREAD

**Issue by liam-middlebrook** [redxdev/hvzsite-old#69]
The formatting for the ID Card Printout sheets is bad. This is because a non-monospace font is being used. Maybe it would be a good idea to use a font like [Ubuntu Mono](http://font.ubuntu.com/)

**Comment by redxdev** [comment]
Using ubuntu mono

**Comment by liam-middlebrook** [comment]
Fixed in https://github.com/redxdev/hvzsite/commit/9ae5a9a1f5ce16e556ed40876cadd0a16227ed65

**Comment by redxdev** [comment]
Not sure how I like the font, actually. I'm going to look into using other fonts.

![card image](http://i.imgur.com/wKLWi5M.png)

**Comment by liam-middlebrook** [comment]
Sounds good, just make sure whatever is used is legible and monospace.
