### ISSUE TITLE
Create Account Activation Notification System ("Do Not Fly List")

### ISSUE THREAD

**Issue by liam-middlebrook** [redxdev/hvzsite-old#82]
Create a system that will allow admins to set notifications for when certain emails are being activated. This will be useful if it is known beforehand that a player must clear something with the admins before being allowed to participate in the game.
- [ ] Store emails for the system
- [ ] Notify mods/admins when "activating" the users account
- [ ] Store custom messages with emails

**Comment by redxdev** [comment]
I want to avoid emails. Just mark an account during activation.

**Comment by liam-middlebrook** [comment]
I don't think that marking an account during activation would be effective for this system. If the person activating the account was aware then it negates the purpose of having this entire feature.

**Comment by redxdev** [comment]
We only care that mods/admins are alerted on activation. Emailing doesn't help that as we won't be reading those until after the fact. Players can't view the activation page anyway. All we need is to put a little exclamation point on their profile when mods are activating their account and taking pictures.

**Comment by redxdev** [comment]
Also, this is something we'd use for maybe a single person every year.

**Comment by liam-middlebrook** [comment]
I'm not saying that emails are sent out. I'm saying that we keep a list of what users are flagged by storing their emails in a list. RIT DCE based emails shouldn't change so that seems like the easiest way to track users across years.

**Comment by redxdev** [comment]
Oh. Yeah.

**Comment by redxdev** [comment]
Easiest way to do this is probably via Symfony's parameters system:

http://symfony.com/doc/current/components/dependency_injection/parameters.html#array-parameters

**Comment by liam-middlebrook** [comment]
For now I'm just going to do a naive hardcoded implementation for the list. We can optimize it to Symfony's specifics later.

**Comment by redxdev** [comment]
Worksforme. Activation is controlled by src/AppBundle/Controller/Web/Admin/PlayerController.php.

The best function to work in is probably playerEditAction, which shows the form where mods can activate a player. We can pass a variable to the template (see $this->renderView) to show a message to the mod. The template is located in app/resources/views/admin/edit_player.html.twig

**Comment by redxdev** [comment]
I'm assuming you don't know twig too well, so here's the if statement which I'm assuming is the only thing you'll need: http://twig.sensiolabs.org/doc/tags/if.html
